apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-spring-petclinic
  labels:
    app: spring-petclinic
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: spring-petclinic
  template:
    metadata:
      labels:
        app: spring-petclinic
    spec:
      containers:
        - name: petclinic
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}